# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_about_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_about_Dialog(object):
    def setupUi(self, about_Dialog):
        about_Dialog.setObjectName("about_Dialog")
        about_Dialog.resize(491, 716)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files/app_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        about_Dialog.setWindowIcon(icon)
        about_Dialog.setStyleSheet("")
        self.widget = QtWidgets.QWidget(about_Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 481, 711))
        self.widget.setStyleSheet("#widget{\n"
"border: 1px solid lightgrey; \n"
"border-bottom-left-radius: 30px;\n"
"border-top-right-radius: 30px;\n"
"background-color:#ffffff;\n"
"}")
        self.widget.setObjectName("widget")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_3.setGeometry(QtCore.QRect(20, 340, 441, 351))
        self.groupBox_3.setStyleSheet("QGroupBox::title{\n"
"color:white; \n"
"background-color: purple;\n"
"border-radius:4px;padding:1px 3px 1px 3px; \n"
"margin-left:3;}")
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_3 = QtWidgets.QLabel(self.groupBox_3)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 431, 331))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 210, 441, 101))
        self.groupBox_2.setStyleSheet("QGroupBox::title{\n"
"color:white; \n"
"background-color: purple;\n"
"border-radius:4px;padding:1px 3px 1px 3px; \n"
"margin-left:3;}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 431, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 50, 441, 121))
        self.groupBox.setStyleSheet("QGroupBox::title{\n"
"color:white; \n"
"background-color: purple;\n"
"border-radius:4px;padding:1px 3px 1px 3px; \n"
"margin-left:3;}")
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 10, 431, 101))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(160, 310, 121, 40))
        self.pushButton_3.setMinimumSize(QtCore.QSize(48, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("border:0px solid;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("files/about_icons/tabs.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon1)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(130, 10, 201, 48))
        self.pushButton.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border:0px solid;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("files/menuBar_icons/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(36, 36))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 180, 131, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("border:0px solid;")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("files/about_icons/usage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon3)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.about_pushButton = QtWidgets.QPushButton(self.widget)
        self.about_pushButton.setGeometry(QtCore.QRect(430, 10, 30, 30))
        self.about_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.about_pushButton.setStyleSheet("QPushButton{\n"
"border:0px solid; border-radius:15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color : #EFE4B0;\n"
"}\n"
"\n"
"")
        self.about_pushButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("files/contacts_icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.about_pushButton.setIcon(icon4)
        self.about_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.about_pushButton.setObjectName("about_pushButton")

        self.retranslateUi(about_Dialog)
        self.about_pushButton.clicked.connect(about_Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(about_Dialog)

    def retranslateUi(self, about_Dialog):
        _translate = QtCore.QCoreApplication.translate
        about_Dialog.setWindowTitle(_translate("about_Dialog", "Amazon Books Scraper - About"))
        self.groupBox_3.setTitle(_translate("about_Dialog", "Info."))
        self.label_3.setText(_translate("about_Dialog", "The App includes 3 tabs: ISBNs to fetch, Fetch Errors, and All books. \n"
"ISBNs to fetch: It’s used to choose CSV file to fetch all ISBNs included and then save them to CSV file for later use. This tab has a progressbar to see the fetching progress and has two counts for books already in the database (no need to fetch again) and for fetched books.  It has a console box to see the get or error occurring during the fetching process. \n"
"Fetch Errors: It’s used to show a table of all errors occurred during fetching books contents and a counter for how many errors there are. Users can search for those error in google immediately by right clicking on them. Users can delete errors or save them to a CSV file. \n"
"All books: It’s used to show all books in the database and counter for how many books had been fetched so far. Users can right click on any books to see its content in a separate window or in web browser in amazon.com. This tab allows to save all books in a CSV file. "))
        self.groupBox_2.setTitle(_translate("about_Dialog", "Info."))
        self.label_2.setText(_translate("about_Dialog", "The App stores the fetched books contents to a local database (SQLite file) and gets ISBNs from a CSV file chosen by a user. Users can fetch and store fetched books or all books as CSV file for research usage later. "))
        self.groupBox.setTitle(_translate("about_Dialog", "Info."))
        self.label.setText(_translate("about_Dialog", "Amazon Books Scraper is an application to fetch books contents and features from amazon.com famous website. The app uses ISBN ID of any books to scrape Title, Author, Category, Sub-Category, Description, Publisher, Year of Publication, Language, Number of Pages, and the Cover Image. "))
        self.pushButton_3.setText(_translate("about_Dialog", " Tabs:"))
        self.pushButton.setText(_translate("about_Dialog", " About The App:"))
        self.pushButton_2.setText(_translate("about_Dialog", " Usage:"))
