# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled_contacts_Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_contacts_Dialog(object):
    def setupUi(self, contacts_Dialog):
        contacts_Dialog.setObjectName("contacts_Dialog")
        contacts_Dialog.resize(458, 498)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("files/app_icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        contacts_Dialog.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(contacts_Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 451, 491))
        self.widget.setStyleSheet("#widget{\n"
"border: 1px solid lightgrey; \n"
"border-bottom-left-radius: 30px;\n"
"border-top-right-radius: 30px;\n"
"background-color:#ffffff;\n"
"}")
        self.widget.setObjectName("widget")
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 40, 411, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setStyleSheet("QGroupBox::title{\n"
"color:white; \n"
"background-color: purple;\n"
"border-radius:4px;padding:1px 3px 1px 3px; \n"
"margin-left:3;}")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(100, 20, 301, 111))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:darkred")
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 20, 81, 121))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("files/contacts_icons/md90.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 200, 411, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setStyleSheet("QGroupBox::title{\n"
"color:white; \n"
"background-color: purple;\n"
"border-radius:4px;padding:1px 3px 1px 3px; \n"
"margin-left:3;}")
        self.groupBox.setObjectName("groupBox")
        self.contactResearchgate_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.contactResearchgate_pushButton.setGeometry(QtCore.QRect(10, 60, 391, 48))
        self.contactResearchgate_pushButton.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.contactResearchgate_pushButton.setFont(font)
        self.contactResearchgate_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactResearchgate_pushButton.setStyleSheet("QPushButton{border:0px solid;}\n"
"QPushButton::hover{ \n"
"color:blue;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton::pressed{ \n"
"color:red;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("files/contacts_icons/rg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactResearchgate_pushButton.setIcon(icon1)
        self.contactResearchgate_pushButton.setIconSize(QtCore.QSize(36, 36))
        self.contactResearchgate_pushButton.setObjectName("contactResearchgate_pushButton")
        self.contactTwitter_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.contactTwitter_pushButton.setGeometry(QtCore.QRect(0, 140, 311, 48))
        self.contactTwitter_pushButton.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.contactTwitter_pushButton.setFont(font)
        self.contactTwitter_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactTwitter_pushButton.setStyleSheet("QPushButton{border:0px solid;}\n"
"QPushButton::hover{ \n"
"color:blue;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton::pressed{ \n"
"color:red;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("files/contacts_icons/twitter.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactTwitter_pushButton.setIcon(icon2)
        self.contactTwitter_pushButton.setIconSize(QtCore.QSize(36, 36))
        self.contactTwitter_pushButton.setObjectName("contactTwitter_pushButton")
        self.contactKaggle_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.contactKaggle_pushButton.setGeometry(QtCore.QRect(20, 100, 291, 48))
        self.contactKaggle_pushButton.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.contactKaggle_pushButton.setFont(font)
        self.contactKaggle_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactKaggle_pushButton.setStyleSheet("QPushButton{border:0px solid;}\n"
"QPushButton::hover{ \n"
"color:blue;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton::pressed{ \n"
"color:red;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("files/contacts_icons/kaggle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactKaggle_pushButton.setIcon(icon3)
        self.contactKaggle_pushButton.setIconSize(QtCore.QSize(36, 36))
        self.contactKaggle_pushButton.setObjectName("contactKaggle_pushButton")
        self.contactLinkedin_pushButton = QtWidgets.QPushButton(self.groupBox)
        self.contactLinkedin_pushButton.setGeometry(QtCore.QRect(10, 20, 401, 48))
        self.contactLinkedin_pushButton.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.contactLinkedin_pushButton.setFont(font)
        self.contactLinkedin_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contactLinkedin_pushButton.setStyleSheet("QPushButton{border:0px solid;}\n"
"QPushButton::hover{ \n"
"color:blue;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton::pressed{ \n"
"color:red;\n"
"font: bold 8pt \"MS Shell Dlg 2\";\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("files/contacts_icons/linkedin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contactLinkedin_pushButton.setIcon(icon4)
        self.contactLinkedin_pushButton.setIconSize(QtCore.QSize(36, 36))
        self.contactLinkedin_pushButton.setObjectName("contactLinkedin_pushButton")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(0, 180, 261, 48))
        self.pushButton_3.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_3.setStyleSheet("border:0px solid;")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("files/contacts_icons/hotmail.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_3.setIcon(icon5)
        self.pushButton_3.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 220, 161, 48))
        self.pushButton_6.setMinimumSize(QtCore.QSize(48, 48))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton_6.setStyleSheet("border:0px solid;")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("files/contacts_icons/whatapp.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon6)
        self.pushButton_6.setIconSize(QtCore.QSize(36, 36))
        self.pushButton_6.setObjectName("pushButton_6")
        self.contacts_pushButton = QtWidgets.QPushButton(self.widget)
        self.contacts_pushButton.setGeometry(QtCore.QRect(400, 10, 30, 30))
        self.contacts_pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.contacts_pushButton.setStyleSheet("QPushButton{\n"
"border:0px solid; border-radius:15px;\n"
"}\n"
"\n"
"QPushButton::hover{\n"
"background-color : #EFE4B0;\n"
"}\n"
"\n"
"")
        self.contacts_pushButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("files/contacts_icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.contacts_pushButton.setIcon(icon7)
        self.contacts_pushButton.setIconSize(QtCore.QSize(32, 32))
        self.contacts_pushButton.setObjectName("contacts_pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(70, 10, 301, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(contacts_Dialog)
        self.contacts_pushButton.clicked.connect(contacts_Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(contacts_Dialog)

    def retranslateUi(self, contacts_Dialog):
        _translate = QtCore.QCoreApplication.translate
        contacts_Dialog.setWindowTitle(_translate("contacts_Dialog", "Amazon Books Scraper - Contacts"))
        self.groupBox_2.setTitle(_translate("contacts_Dialog", "Boi."))
        self.label_2.setText(_translate("contacts_Dialog", "I’m Mohammed Deeb, born in 1990. \n"
"I love IT and data science so much. \n"
"I’ve used PyQT5 to build this app. \n"
"\n"
"You can reach me through  the following contacts below:"))
        self.groupBox.setTitle(_translate("contacts_Dialog", "Contacts info."))
        self.contactResearchgate_pushButton.setText(_translate("contacts_Dialog", "  https://www.researchgate.net/profile/Mohammed-Deeb"))
        self.contactTwitter_pushButton.setText(_translate("contacts_Dialog", "  https://twitter.com/MohammedDeeb90"))
        self.contactKaggle_pushButton.setText(_translate("contacts_Dialog", "  https://www.kaggle.com/masteronepiece"))
        self.contactLinkedin_pushButton.setText(_translate("contacts_Dialog", "  https://www.linkedin.com/in/mohammed-deeb-33696b9b"))
        self.pushButton_3.setText(_translate("contacts_Dialog", "  master_md_90@hotmail.com"))
        self.pushButton_6.setText(_translate("contacts_Dialog", "  +963 93 401 2244"))
        self.label_3.setText(_translate("contacts_Dialog", "Amazon Books Scraper - Contacts"))
